- package.json
- src/Filters.js
- src/LogDetailsMetaData.js
- src/MainApp.js
- src/SearchResultList.js
- src/customization.js
- src/utils.js
- src/utils.test.js
Highlights:
1. By default the search query editor (aka advanced search) is hidden. It can be expanded/collapsed using the dedicated button.
2. When search query editor is expanded, the query text field turn to read-only.
3. Layout in the search query editor have been updated to reflect the UI in the Phoebus client.
4. Internal business logic has been updated to make use of a "global" search parameter map.
5. When user edits a text field in the query editor to remove the value (=empty string), that search parameter is removed completely, i.e. it will not propagate to the service when executing the search. 
6. customization.js now defines a default search parameter map instead of a search string.
> Aligning search query editor to Phoebus counterpart

- src/EntryEditor.js
- src/MainApp.js
- src/utils.js
To get an idea of how the service is used with respect to clients (web, Phoebus), a custom HTTP header will be added for calls to create a log entry, and calls to search.
For the service to log the request it needs to be built against commit 0e7d47ed991457ae2cd8a37890060ffb73e08cfd or newer, see https://github.com/Olog/phoebus-olog/commit/0e7d47ed991457ae2cd8a37890060ffb73e08cfd.
> Adding client info HTTP header for logging on service

- package.json
- src/LoginDialog.js
- src/LogoutDialog.js
- src/MainApp.js
- src/SearchResultList.js
Recent updates to Olog service will return a HTTP 400 /bad request) response if user specified time range is invalid, e.g. "start" after "end". Before the update, the service would ignore the time range and - if no other search parameters were specified - match all log entries in the index.
To correctly handle the HTTP 400 status, a few changes have been made to the web client. More specifically, an alert is shown, and the search result list is not updated.
> Handle "bad request" if time range is invalid

- src/components/LogDetails/LogDetails.js
- src/components/LogDetails/NavigationButtons.js
- src/components/LogEntriesView/LogEntriesView.js
Currently, the navigation buttons in the LogDetails view navigate incrementally/decrementally by id rather than over the search results, and it throws a popup when no more data is available.
What it should happen instead is:
- the buttons navigate forwards/backwards through the search results
- when there is no data in a direction, then the button grays out / disables instead of throwing a popup
- when going into the next page of results, the search results view should update to show that page
- whatever result is being shown should be 'active' / colored like when you click on a search result item directly
> CSSTUDIO-1694: navigation buttons should navigate search results

- package-lock.json
- package.json
- src/components/App.test.js
- src/components/Filters/Filters.js
- src/components/LogEntriesView/LogEntriesView.js
- src/components/SearchResult/SearchBox.js
- src/mocks/handlers.js
- src/mocks/server.js
- src/setupTests.js
Adds integration tests for *some but not all* of the use cases for olog web client:
- the app renders at all without crashing (was already in there, but listing it here for brevity)
- a default search is executed when the page loads
- an error banner is shown if the logbook service is unavailable
- when signed in, the username is shown and it's possible to create new log entries
- when signed out, 'login' is displayed instead of username and it's not possible to create new log entries
- users can search by manually entering terms in the search bar and hitting enter
- users can search by opening the filter panel, updating one of the fields, and closing the panel
Excluded are these cases on account of some refactoring needed on the FE first, to make the inputs properly labeled.
- users can …
> Additional tests

- src/components/SearchResult/PaginationBar.js
solution: show pagination control on separate line on large devices, and hide when only one page of results (e.g. eliminate the media-query problem altogether except for the existing case on small devices)
> CSSTUDIO-1780: Pagination controls render outside container on some widths

- src/components/LogDetails/LogEntrySingleView.js
- src/components/shared/input/FileInput.js
- fix: cannot upload files with same name. 
- fix: files using filename instead of unique id, resulting in broken links. 
- fix: attachment images missing alt attribute
Solves #51
> Fix: Same-Name Attachments Render with Broken Image Link

- src/components/shared/HtmlContent.js
Note that indented items require 4 spaces (not 2)
**Requires visual inspection**
Test Markdown: 
```
Favorite Things:
* flowers
* roses
* red roses
* with thorns
* smooth stem
* white roses
* tulips
* birds
* parrots
* cockatiels
* pied coloration
* normal coloration
* budgies
* blue and white
* yellow and green
* solid color
* toucans
* bees
* bumbly ones
* big buzzers
* little buzzers
* stingy ones
Stuff to do:
1. Bake Cookies
1. Mix the wet
1. cream the butter and sugar
1. Mix the dry
1. Bake in the oven
2. Hug Friends
3. Conquer the shadow realm
```
> CSSSTUDIO-1816: markdown list elements not indented

- src/api/olog-service.js
- src/components/EntryEditor/index.js
- src/components/shared/ExternalLink.js
- src/constants/index.js
feature: help link for description commonmark formatting. 
refactor: make app url available as a constant
UX note: since the help link is a secondary action it is on the bottom left, and the other primary-action buttons (embed image, preview) are on the bottom right.
> CSSTUDIO-1831: Add Formatting Link to Description

- .github/pull_request_template.md
- src/components/LogDetails/LogEntryGroupView.js
fix: group view of log entry not styling markdown
> CSSTUDIO-1837: Olog web client group view incorrect styling

- src/api/olog-service.js
- src/components/App.test.js
- src/components/Pagination/index.js
- src/components/Pagination/styles.js
- src/components/SearchResult/PageSizeInput.js
- src/components/SearchResult/PageSizeInput.test.js
- src/components/SearchResult/PaginationBar.js
- src/components/SearchResult/PaginationBar.test.js
- src/components/shared/input/TextInput.js
- src/test-utils/index.js
- src/utils/index.js
- fix: only allow values 1-999 on page size, allow blanks but don't submit them. 
- fix: infinite looping / dependencies in pagination bar. 
- refactor: move delay utility function into utilities file.
> CSSTUDIO-1840: Need to handle "hits per page" being empty

- src/components/Attachment/index.js
- src/components/EntryEditor/EmbedImageDialog.js
- src/components/EntryEditor/EntryEditor.test.js
- src/components/EntryEditor/index.js
- src/components/shared/input/FileInput.js
- src/components/shared/input/LabeledInput.js
- src/components/shared/input/TextInput.js
- Feature: embed image directly into the Description field by pasting it from your clipboard (pasting regular text works as before)
- Refactor: use the same file upload control in the embed image upload as attachments, including with image preview
- Fix: Previous image information remains in the embed image modal after closing or confirming
- Fix: Inaccessible delete attachment button
> Csstudio 1805: Paste Image Embed Feature

- src/components/shared/HtmlContent.js
- style: remove margin-bottom on hr markup, to match Java client style
> CSSTUDIO-1854: Shrink margin below horizontal ruler

- src/components/LogDetails/LogEntryGroupView.js
- src/components/LogDetails/LogEntrySingleView.js
- src/components/LogEntriesView/index.js
- src/config/media.js
- style: horizontal scrollbar should only appear on log entries, not on entire app 
- fix: jittering on some screens caused by appearance of horiz scrollbar when clicking wide log entries
> CSSTUDIO-1843: Visual jittering when clicking some log entries (caused by horiz scrollbar)

- src/components/App.js
- src/components/Banner/index.js
- src/components/shared/SkipToContent.js
- src/index.js
- Wraps banner in header
- Places nav elements in ul / li
- Adds "skip to main content" link
- Uses main element for app content
> Csstudio 1855 - Accessible / Semantic Banner

- src/api/olog-service.js
- src/components/App.js
- src/components/App.test.js
- src/components/Banner/index.js
- src/components/EntryEditor/index.js
- src/components/shared/Button.js
- src/components/shared/Button.test.js
- src/index.js
- buttons are accessible via keyboard when disabled, but otherwise appear disabled and do not execute any actions
- Create New Log Entry button is now a link (not both a button and link; improved semantics / accessibility)
- refactor: move session check to log entry form on load
Note, there is a larger UX question here of whether we should even show the New Log Entry button at all when the user isn't logged in. Disabled links don't make sense, so this favors removing the link completely if not logged in. However, users have come to expect that link to be there and be "disabled" when not logged in.
> CSSTUDIO-1856: Accessible disabled buttons

- src/components/Attachment/index.js
- src/components/EntryEditor/EntryEditor.test.js
- src/components/EntryEditor/index.js
- fix: could not attach many attachments simultaneously in the log entry form
- fix: sometimes form may submit due to button type 'default' when deleting an attachment from the form
> Csstudio-1867: Attach multiple attachments Olog web client

- src/components/EntryEditor/index.js
- src/components/shared/HtmlContent.js
When inserting markdown, the html generated may include paragraph elements instead of raw text in the list elements. In those cases, the elements were being rendered on the next line from the bullet rather than the same line. 
This PR also includes changes to:
- spacing around list elements and proceeding/preceeding text
- alternating bullet styles on indented elements
> Csstudio-1886: Display of Markdown List Elements Containing Paragraphs

- e2e/cypress/e2e/happy-paths.cy.js
- src/components/App.test.js
- src/components/Filters/index.js
Adds title to advanced search (ux)
Updates role of form to "search" per https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/form_role
> CSSTUDIO-1893: add title to advanced search

- src/components/shared/HtmlContent.js
Fixes issue where ordered lists are styled as unordered lists (as bullet points). Was introduced by nested list CSS.
> CSSTUDIO-1933: fix styling of ordered lists

- src/components/App.test.js
- src/components/EntryEditor/EmbedImageDialog.js
- src/components/EntryEditor/EntryEditor.js
- src/components/shared/input/FileInput.js
- src/utils/customization.js
**NOTE: integration test requires new version of Olog service, available on branch CSSTUDIO-1818 in the service repo.**
> New endpoint to create log entry plus all attachments in single multipart request

- package-lock.json
- package.json
- src/components/Banner/Banner.js
- src/components/shared/input/TextInput.js
- fixes crash that can be invoked by clicking sign-in, cancelling (or signing-in), then your profile button (cause was incorrectly mapped ref to MUI TextField)
- updates version of react-hook-form
- updates package version in package-lock file
> CSSTUDIO-2033: fix TextInput crash on bad ref focus

- README.md
- src/api/ologApi.js
- src/api/ologApi.test.js
- src/components/Filters/Filters.js
- src/components/log/CreateLog/CreateLog.js
- src/components/log/EditLog/EditLog.js
- src/components/log/EntryEditor/Description/Description.js
- src/components/log/EntryEditor/EntryEditor.js
- src/components/log/ReplyLog/ReplyLog.js
- src/components/shared/input/managed/EntryTypeSelect.js
- adds EntryType dropdown to filters, like in the phoebus client
- adds test for some utilities
> CSSTUDIO-2065: add entryType to filters

- src/components/LogDetails/GroupHeader.js
- src/components/LogDetails/LogDetails.js
- src/components/LogDetails/LogDetailsMetaData.js
- src/components/LogDetails/LogEntryGroupView.js
- src/components/LogDetails/LogEntrySingleView.js
migrates the group and single entry log views to MUI
> CSSTUDIO-1983: migrate single and group entry views to mui

- README.md
- lists environment variables in table format for easier reading
- removes deployment information; there is nothing special about this frontend that differs from other React apps that isn't already noted (removes Apache Tomcat example)
- review and cleanup readme organization otherwise
> remove extraneous info from readme, simplify layout

- .gitignore
- src/beta/components/log/LogDetails/LogHeader.js
- src/components/LogDetails/LogDetailsMetaData.js
- src/components/SearchResult/SearchResultItem.cy.js
- src/components/SearchResult/SearchResultItem.js
It can be confusing when in the search result list the create date is ABC, but in the log entry it is actually the edited date DEF. 
This updates the UX such that:
- the log entry always shows the create date
- if edited, the text becomes "(edited DEF)" in the same date format as the result lis
> CSSTUDIO-2318: always use create date in log details

- src/beta/components/search/SimpleSearch/SimpleSearch.js
Adds "from: " to the data pill to date search clearer:
Adding date-range picker being put on hold, as that component isn't freely available in MUI without a license.
> CSSTUDIO-2334: refine beta date selector

- src/components/Attachment/AttachmentImage.js
- src/components/log/EntryEditor/Description/OlogAttachment.js
In some cases, images don't display properly because their mime-type is image/{something} and a few pieces of code were asserting this was equal to "image" rather than starting with that text.
I'm aware there are two places in the code performing the check, however I'd rather plan tackling that in a separate body of work.
> CSSTUDIO-2373: fix images not displayed in some cases

- src/api/ologApi.js
- src/beta/components/search/SearchResults.js
- src/components/LogDetails/LogEntryGroupView.js
- src/components/LogDetails/NavigationButtons.js
- src/components/log/CreateLog/CreateLog.js
- src/components/log/EditLog/EditLog.js
- src/components/log/ReplyLog/ReplyLog.js
- src/hooks/useBetaNavigate.js
- adds redirect in create, edit, and reply to `finally` clause to ensure it always happens even when log verification fails
- centralizes beta navigation to custom hook
All component and end-to-end tests pass, please ignore GitHub flake.
> CSSTUDIO-2461: fix fail to redirect on create, edit, reply

- src/beta/components/search/SearchResultList/SearchResultList.jsx
- src/beta/components/search/SearchResults.js
- src/hooks/useKeyPress.js
- Added new hook for listening to keypress events
- Refactored and added new logic to accommodate keyboard navigation of entries
> CSSTUDIO-2728: Add keyboard navigation of entries

- src/beta/components/log/LogDetails/LogDetails.jsx
- src/beta/components/navigation/AppNavBar/AppNavBar.jsx
- src/beta/components/search/AdvancedSearchDrawer.jsx
- src/beta/components/search/SearchParamsBadges.jsx
- src/beta/components/search/SortToggleButton.jsx
- src/components/log/EntryEditor/EntryEditor.jsx
- src/components/log/LogContainer.jsx
- src/components/shared/input/FileInput.jsx
- Refetch log details after edit
- Match color of filter and sort icons to the date icon in search field
- Give create log page a maxWidth and center fields
- Remove unused imageUrlPrefix prop
- Rename advanced filter field from "Text" to "Description", searching still works by using desc=...
- Made cloudIcon fit inside box for adding attachments
> cleanup and small fixes

- src/beta/utils/parseEmbeddedImages.js
- src/components/log/EntryEditor/Description/Description.jsx
- src/components/log/EntryEditor/Description/HtmlPreviewModal.jsx
- src/components/shared/CommonMark/CommonMark.jsx
- Changed logic to save attachment with relative url aka "attachment/..."
- Moved parsing logic into reusable function
- Used function for preview modal and implemented for rendering markdown in log entry details
> CSSTUDIO-3171: Embed images

- src/components/log/EditLog/EditLog.jsx
- src/components/log/EntryEditor/Description/Description.jsx
- src/components/log/EntryEditor/EntryEditor.jsx
Changed the name of attachmentDisabled to a more generic isEditing variable to indicate the meaning of it.  
The choice is due to the attachmentDisabled being also used for, at least, one more thing other than disabling attachment and it also being a one to one to when  a user is editing an entry. This sohuld represent better the variable meaning and not change any of the functionalities
> Changed the name of attachmentDisabled to isEditing
