Olog/phoebus-olog-web-client

src/LogDetails.js

Button to copy URL. No check on access, authorization, etc.

Added Copy URL button to log details entry

---

src/EntryEditor.js
src/HtmlPreview.js
src/image-processor.js
src/utils.js

1. HTML preview was setting global flags that were causing problems for image-processing for Log details view. Resolved it.
2. The search string should not start with "&" character. Ideally "&" should only be in between search parameters. Fixed it.

1. HTML preview was causing problems in image-processing for log details view.

---

src/Filters.js
src/MainApp.js
src/SearchResultList.js
src/css/olog.css
src/utils.js

This is to align with changes in the Phoebus client, see https://github.com/ControlSystemStudio/phoebus/pull/2217

Search tool makeover + support for attachment filtering

---

package-lock.json
package.json
src/components/Filters/Filters.js
src/components/Logbooks/Logbooks.js
src/components/MainApp.js
src/components/SearchResult/SearchBox.js
src/components/SearchResult/SearchResultList.js
src/components/Tags/Tags.js
src/utils/searchParams.js
src/utils/searchParams.test.js
src/utils/utils.js
src/utils/utils.test.js

This ended up being a much heavier refactor than expected, due to discovering duplicate of the queryParams state in one of the nested components, and the general mixing of search query string and its object representation. So this includes:
- refactoring several components into functional components; this makes props/inputs clearer to read, and state a bit easier to manage
- updating/adapating many components to be managed components; e.g. so their state is managed by React rather than by ref/html
- updating the query param functions to support parsing and deserializing proper query param objects. Since this is already a solved problem, I've added the query-string library and tests to verify this was configured correctly.
If there is anything I'm missing in all this, please let me know! …

Csstudio 1677 - Refactor Search Bar into Managed Component

---

src/components/App.js
src/components/Filters/CollapsibleFilters.js
src/components/LogDetails/LogEntryGroupView.js
src/components/LogEntriesView/LogEntriesView.js
src/components/SearchResult/SearchResultList.js

- duplicate searches and react warnings. 
- refactor: converted App to functional component. 
- refactor: moved filter collapse into dedicated component with local search params that are used to update actual search params on filter collapse

fix: warnings and duplicate search on enter

---

src/components/Filters/CollapsibleFilters.js
src/components/Filters/Filters.js
src/components/LogDetails/LogDetails.js

feature: filters submit on enter, on changes to dropdowns and sort, and on closing start/end date dialogue

CSSSTUDIO-1700: More Filter View Search Triggers

---

package-lock.json
package.json
src/components/App.js
src/components/Banner/Banner.js
src/components/Filters/CollapsibleFilters.js
src/components/LogEntriesView/LogEntriesView.js
src/components/SearchResult/PaginationBar.js
src/components/SearchResult/SearchBox.js
src/components/SearchResult/SearchBoxInput.js
src/components/SearchResult/SearchResultList.js

refactor: broke up search box inputs etc to improve style readability
fix: pagination items force entire page scroll rather than sitting inside their container. 
refactor: pagination controls moved to top on small devices

CSSTUDIO-1716: More Cosmetic Fixes

---

package-lock.json
package.json
src/components/EntryEditor/EntryEditor.js
src/components/LoadingOverlay/LoadingIoLdsRing.css
src/components/LoadingOverlay/LoadingIoLdsRing.js
src/components/LoadingOverlay/LoadingOverlay.css
src/components/LoadingOverlay/LoadingOverlay.js
src/components/LoadingOverlay/LoadingOverlaySpinner.css
src/components/LoadingOverlay/LoadingOverlaySpinner.js
src/components/SearchResult/SearchResultList.js

Replaces LoadingOverlay with custom / self-managed component; existing library not compatible with React 17+, and the functionality is low-to-moderate effort to replicate.
This should wrap up the prep steps for upgrading react.

Csstudio 1689

---

package-lock.json
package.json
src/components/App.test.js
src/components/EntryEditor/EntryEditor.js
src/components/Filters/DateSelectorModal.js
src/components/Filters/Filters.js
src/components/Logbooks/Logbooks.js
src/components/Tags/Tags.js

Notably, this leaves out tests for creating new log entries as there are issues with the ref-controlled inputs in the EntryEditor component, and this would require additional work to make testable.

Csstudio 1732 - labeled/accessible/testable inputs in advanced search filter

---

src/components/EntryEditor/index.js

fix: require at least one logbook on log entries

Validation on Log Entries

---

src/components/Filters/index.js
src/components/SearchResult/SearchBoxInput.js
src/features/searchParamsReducer.js
src/services/ologApi.js

refactor: when user doesn't change a search, then they should still be able to submit the same search again

Allow Force Retry of Unchanged Query

---

.github/pull_request_template.md
src/components/App.js
src/components/App.test.js
src/components/Banner/index.js
src/components/EntryEditor/EntryEditor.test.js
src/components/EntryEditor/index.js
src/components/LogDetails/LogDetails.test.js
src/components/LogDetails/LogEntryGroupView.js
src/components/LogDetails/LogEntrySingleView.js
src/components/LogDetails/NavigationButtons.js
src/components/LogDetails/index.js
src/components/LogEntriesView/LogEntriesView.test.js
src/components/LogEntriesView/index.js
src/components/Pagination/index.js
src/components/Pagination/styles.js
src/components/SearchResult/PaginationBar.js
src/components/SearchResult/SearchBoxInput.js
src/components/SearchResult/SearchResultItem.js
src/components/SearchResult/SearchResultList.js
src/components/SearchResult/SearchResultList.test.js
src/components/shared/VisuallyHiddenText.js
src/components/shared/input/FileInput.js
src/components/shared/input/LabeledInput.js
src/index.js
src/mocks/handlers.js
src/setupTests.js
src/test-utils/index.js

Adds integration and unit tests for previously manually-tested parts of the application.
Refactors a few components as part of testing/accessibility (as they go hand-in-hand)

CSSTUDIO-1813: Various Tests

---

src/components/EntryEditor/index.js

Fixing - hopefully - bug in Reply action

---

src/components/EntryEditor/OlogAttachment.js

- Updates the Attachment model per the API changes in https://github.com/Olog/phoebus-olog/pull/173
n/a

CSSTUDIO-2024: update attachment model per api changes

---

src/mocks/handlers.js
src/setupTests.js

Makes some smaller changes to improve test consistency (false negatives) due to timeout issues. 
Won't be making fixes to the root causes until the conversion to MUI is complete (there are a few components, once removed, to alleviate these problems)

investigation / improve test consistency

---

src/beta/components/search/SearchResultList/SearchResultList.js
src/beta/components/search/SimpleSearch/SimpleSearch.js
src/beta/components/search/SimpleSearch/index.js
src/components/shared/input/WizardDateInput.js
src/hooks/useSanitizedSearchParams.js
src/views/App.cy.js

- adds initial beta "simple search" component with stubbed search param and date picker.
- uses start date for the date picker
- keeps ascending/descending toggle in same place, will address in workshop

Csstudio 2220 search initial beta

---

src/components/LogDetails/LogDetails.js
src/components/LogDetails/NavigationButtons.js
src/views/App.cy.js

Reverts Olog/phoebus-olog-web-client#145

Revert "CSSTUDIO-2059: deprecate log nav buttons"

---

src/api/ologApi.js

Followup from #151 where a change to the olog api call was missed; result was that after creating/editing/replying to a log, it would spin forever but the log would still be created. 
This is caused by passing the arguments incorrectly in the check condition that verifies a created log has its attachments etc available before redirecting the user.
Ran tests locally and verified component and e2e tests pass as expected.

fix wrong check condition after created/edit/reply

---

src/beta/components/log/LogDetails/KeyValueTable.jsx
src/beta/components/log/LogDetails/LogDetails.js
src/beta/components/log/LogDetails/LogDetailsWithReplies.js
src/beta/components/log/LogDetails/LogHeader.js
src/beta/components/log/LogDetails/LogProperty.js
src/beta/components/log/LogDetails/MetadataTable.js
src/beta/components/search/SearchResults.js

Title + refactor components.
@shroffk  Please don't merge until tested and approved by @georgweiss

Rework Pills, rework spacing and alignments, Refactor properties

---

src/components/log/EntryEditor/EntryEditor.js

Add form validation for Entry Type select field

---

.env.example
README.md
scripts/install-dependencies-and-build.sh
src/components/shared/input/managed/EntryTypeSelect.js
src/config/customization.js

More flexible way to customize Level values

---

.env.example
src/config/customization.js

Changed customization also for default 'level'

---

src/api/ologApi.js
src/beta/components/search/AdvancedSearchDrawer.jsx
src/beta/components/search/SearchParamsBadges.jsx
src/beta/components/search/SearchResultList/SearchResultSingleItem.jsx
src/features/advancedSearchReducer.js
src/features/searchParamsReducer.js

Allow users to search for properties

CSSTUDIO-2818: Allow properties in search

---

src/beta/components/search/SearchResultList/SearchResultList.jsx
src/beta/components/search/SearchResults.jsx
src/beta/views/BetaApp.jsx
src/beta/views/SearchView.jsx

CSSTUDIO-2950: Fix scroll bug

---

src/beta/components/search/SearchResultList/SearchResultGroupItem/SearchResultGroupItem.jsx
src/beta/components/search/SearchResultList/SearchResultList.jsx
src/beta/components/search/SearchResultList/SearchResultSingleItem.jsx
src/beta/components/search/SearchResults.jsx
src/components/LogDetails/LogEntryGroupView.jsx
src/components/LogDetails/NavigationButtons.jsx
src/components/SearchResult/SearchResultList.jsx
src/components/log/LogContainer.jsx

- Reverted to the old logic of grouping "replies"
- Changed the terminology from replies to group in the expand button
- Added new reply icon and design temporarily (will hopefully get feedback on that from balazs) but the logic, ordering behavior is how I want it right now at least
- Reduced size of the replies

Csstudio 2963 grouping replies bug

---

src/beta/components/log/LogDetails/KeyValueTable.jsx
src/beta/components/log/LogDetails/LogHeader.jsx
src/components/log/EntryEditor/EntryEditor.jsx
src/components/log/LogHistory/LogHistory.jsx

- Made sure timestamps are correct as well as "edited" vs "created" keys
- Cleaned up design a little bit - definately not the final version but looks a bit more coherant now
- Cleaned up some other small UI things, making owner and date bold instead of the keys author/date for example

Csstudio-2991: history page bug

---

src/components/log/EntryEditor/Description/Description.jsx
src/components/log/EntryEditor/Description/HtmlPreviewModal.jsx
src/components/shared/CommonMark/CommonMark.jsx

- Added base url to embedded images
- Replace remote image urls with local blobs for preview pruposes

Csstudio 3027 embeded images

---

src/beta/components/log/TagChip.jsx
src/beta/components/search/AdvancedSearchDrawer.jsx
src/beta/components/search/SearchResultList/SearchResultGroupItem/SearchResultGroupItem.jsx
src/beta/components/search/SearchResultList/SearchResultList.jsx
src/beta/components/search/SearchResultList/SearchResultSingleItem.jsx
src/beta/components/search/SearchResults.jsx
src/beta/components/search/SimpleSearch.jsx
src/components/shared/input/WizardDateInput.jsx
src/features/searchParamsReducer.js

[Jira ticket](https://jira.ess.eu/secure/RapidBoard.jspa?rapidView=1247&projectKey=CSSTUDIO&view=detail&selectedIssue=CSSTUDIO-3030&quickFilter=6031#)
- Removed datepicker from searchbar
- Changed "Today" to "Now"
- Added filtering of date range for groups/replies so that you only see what is withtin the range in list view
- Remember date picked when opening the datepicker again
- Fixing diverse bugs

CSSTUDIO-3030: Solve datepicker issues

---

src/beta/components/log/LogDetails/LogAttachmentsHeader.jsx
src/beta/components/log/LogDetails/LogDetails.jsx
src/beta/components/search/AdvancedSearchDrawer.jsx
src/beta/components/search/SearchParamsBadges.jsx
src/beta/components/search/SearchResultList/SearchResultSingleItem.jsx
src/beta/components/search/SimpleSearch.jsx
src/components/shared/CommonMark/CommonMark.jsx

- Make sure summary is formatting in plain text, not rendered html
- Also added fix for [CSSTUDIO-3036](https://jira.ess.eu/browse/CSSTUDIO-3036)

CSSTUDIO-3033: Format summary correctly

---

src/beta/components/log/LogDetails/LogDetailsWithReplies.jsx
src/beta/components/search/SearchResultList/SearchResultGroupItem/SearchResultGroupItem.jsx

- Expand log details by default
- Highlight selected log 
- Also has fix for [CSSTUDIO-3066](https://jira.ess.eu/browse/CSSTUDIO-3066)

Csstudio-3028: Expand and highlight

---

src/beta/components/log/LogDetails/LogDetailActionButton.jsx
src/beta/components/navigation/AppNavBar/AppNavBar.jsx
src/components/Banner/Banner.jsx
src/components/log/LogContainer.jsx
src/hooks/useBetaNavigate.js
src/providers/RouterProvider.jsx

Moving the beta url paths to root and moving old olog to /legacy. Preparing for deployment of 2.0.0.

CSSTUDIO-3093: Deploy olog 2.0.0

---

src/beta/components/log/LogDetails/AttachmentsGallery.jsx
src/beta/components/log/LogDetails/CopyUrlButton.jsx
src/beta/components/log/LogDetails/LogDetailActionButton.jsx
src/beta/components/log/LogDetails/LogDetailsWithReplies.jsx
src/beta/components/navigation/AppNavBar/AppNavBar.jsx
src/beta/components/search/AdvancedSearchDrawer.jsx
src/beta/components/search/SimpleSearch.jsx
src/beta/components/search/SortToggleButton.jsx
src/beta/utils/isHomePage.js
src/beta/views/BetaApp.jsx
src/beta/views/SearchView.jsx
src/components/LoginLogout/LoginDialog.jsx
src/components/log/EditLog/EditLog.jsx
src/components/log/EntryEditor/Description/Description.jsx
src/components/log/EntryEditor/EntryEditor.jsx
src/components/log/ReplyLog/ReplyLog.jsx
src/components/shared/Help.jsx
src/components/shared/input/MultiSelect.jsx
src/components/shared/input/TextInput.jsx
src/components/shared/input/WizardDateInput.jsx
src/components/shared/input/managed/EntryTypeSelect.jsx
src/features/advancedSearchReducer.js

Commit history is a good list for all the individual changes made.

Csstudio 3114 feedback anders

---

src/beta/components/log/LogDetails/AttachmentsGallery.jsx
src/beta/components/log/LogDetails/LogAttachmentsHeader.jsx
src/beta/components/log/LogDetails/LogDetailActionButton.jsx
src/beta/components/log/LogDetails/LogDetails.jsx
src/beta/components/log/LogDetails/LogDetailsWithReplies.jsx
src/beta/components/log/LogDetails/LogHeader.jsx
src/beta/components/log/LogDetails/MetadataTable.jsx
src/beta/components/navigation/AppNavBar/AppNavBar.jsx
src/beta/components/search/SearchResultList/SearchResultGroupItem/SearchResultGroupItem.jsx
src/beta/components/search/SearchResultList/SearchResultSingleItem.jsx
src/beta/components/search/SimpleSearch.jsx
src/components/log/EntryEditor/Description/Description.jsx
src/components/shared/CommonMark/HtmlContent.jsx
src/components/shared/input/MultiSelect.jsx
src/components/shared/input/TextInput.jsx
src/components/shared/input/WizardDateInput.jsx

- Adjust font sizes
- Added tooltips around action icons in search results logs list (edited, attachment and reply)

CSSTUDIO-3155: Adjust font sizes + CSSTUDIO-3132: Add tooltips

---

src/beta/components/log/LogDetails/AttachmentsGallery.jsx

- Added download tag
- Increased image size and improved responsiveness
- Moved arrow buttons closer together for easier navigation

CE-3138: download image fix, increase image size, move arrow buttons

---

.env.example
README.md
scripts/install-dependencies-and-build.sh
src/api/ologApi.js
src/beta/components/log/LogDetails/AttachmentsGallery.jsx
src/components/log/EntryEditor/EntryEditor.jsx
src/components/shared/input/managed/EntryTypeSelect.jsx
src/config/customization.js

Fetch level values from service

Csstudio 3190 level values

---

src/components/log/EntryEditor/EntryEditor.jsx

Noticed that the default value wasn't populating properly for edit and reply views. This is a fix for that

CSSTUDIO-3190: Fix reply, edit views

---

src/beta/components/log/LogDetails/LogDetailActionButton.jsx
src/beta/components/log/LogDetails/LogDetails.jsx
src/beta/components/log/LogDetails/LogDetailsWithReplies.jsx
src/beta/components/log/LogDetails/LogHeader.jsx
src/beta/components/log/LogDetails/MetadataTable.jsx
src/beta/components/search/SearchResultList/SearchResultList.jsx
src/beta/utils/isHomePage.js
src/providers/RouterProvider.jsx

- Fixed scroll to specific log entry from url visit
- Added ID to detailsview
- Fixed some routes

CSSTUDIO-3141: Fix scroll + CSSTUIO-3142: Add ID

---

src/beta/components/search/SimpleSearch.jsx

improve contrast on search field

CSSTUDIO-3193: Improve contrast on search bar

---

src/beta/components/log/LogDetails/MetadataTable.jsx
src/beta/components/search/AdvancedSearchDrawer.jsx
src/beta/components/search/SearchParamsBadges.jsx
src/beta/components/search/SearchResults.jsx
src/components/shared/input/managed/EntryTypeSelect.jsx
src/features/advancedSearchReducer.js
src/features/searchParamsReducer.js
src/hooks/useSanitizedSearchParams.js

Now you can filter with multiple entry types. Took a while to get this to work because of how convoluted the code structure for this is. Hopefully can be improved in the future.

CSSTUDIO-2909: Allow filtering with multiple entry types

---

src/components/Attachment/AttachmentImage.jsx
src/components/log/LogDetails/AttachmentsGallery.jsx

Most likely introduced while cleaning up the legacy code. Reverted these changes and made small adaptation.

Fix undefined attachment url bug

---

package-lock.json
package.json
src/components/Attachment/AttachmentImage.jsx
src/components/log/EntryEditor/Description/Description.jsx
src/components/log/LogDetails/AttachmentsGallery.jsx

- Makes sure to show correct preview image and file image in create form file/image upload
- Shows correct file image icon in log entry

Csstudio 3299 fileimage overlay

---

src/components/log/EntryEditor/Description/Description.jsx
src/mocks/handlers.js
src/stories/SearchResultList.stories.jsx
src/test-utils/rtl-utils.jsx

- changed rest call to msw v2 correct http calls
- adjusted response handling
Closes #240

msw v2 fix

---

src/components/shared/input/Checkbox.jsx

Change Checkbox.js labelPlacement to valid value
Closes #238

fixed MUI Checkbox label issue

---

src/components/log/CreateLog/CreateLog.jsx
src/components/log/EditLog/EditLog.jsx
src/components/log/EntryEditor/EntryEditor.jsx
src/components/log/ReplyLog/ReplyLog.jsx
src/mocks/fixtures/generators.js

Sets correct level value for each of the views (edit, reply, create).

CSSTUDIO-3363: Entry type undefined

---

.github/workflows/e2e.yml
.github/workflows/test.yml

we have a backlog ticket for fixing the tests. In the meanwhile it's unnecessary to get all the failed runs.

comment out tests til fixed

---

src/components/search/SearchResultList/SearchResultGroupItem/SearchResultGroupItem.jsx
src/components/search/SearchResultList/SearchResultList.jsx

You can now open replies by clicking left or right arrow

CSSTUDIO-3358: Keyboard expand replies

---

src/components/log/EntryEditor/Description/Description.jsx

CSSTUDIO-3419: text/plain specific regex

---

eslint.config.js
package-lock.json
package.json

Was not working so decided to start from scratch. Cleaned out some unnecessary and redundant rules as well.

Fix eslint flat config and clean up

---

src/components/AppNavBar/AppNavBar.jsx
src/components/log/EntryEditor/Description/Description.jsx
src/components/log/EntryEditor/Description/EmbedImageDialog.jsx
src/components/shared/UnsupportedAlert.jsx
src/components/shared/input/FileInput.jsx
src/hooks/useUnsupported.js

CSSTUDIO-2944: Handle unsupported file format (HEIC)
